// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE_qJqdkBliD0QdCXA5ot3I9RQU0QHw0I',
    appId: '1:244933357952:web:4dc0ed92f6f5afa627d165',
    messagingSenderId: '244933357952',
    projectId: 'restauranteb-d5673',
    authDomain: 'restauranteb-d5673.firebaseapp.com',
    storageBucket: 'restauranteb-d5673.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr5-ejzBC00Omsfuxwl6SRZifodx8V-ck',
    appId: '1:244933357952:android:e7e66060f9ddc79b27d165',
    messagingSenderId: '244933357952',
    projectId: 'restauranteb-d5673',
    storageBucket: 'restauranteb-d5673.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFmSpfVMz0kQe884ZWHSoYjN0-77olSUw',
    appId: '1:244933357952:ios:1c9380409713722c27d165',
    messagingSenderId: '244933357952',
    projectId: 'restauranteb-d5673',
    storageBucket: 'restauranteb-d5673.appspot.com',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFmSpfVMz0kQe884ZWHSoYjN0-77olSUw',
    appId: '1:244933357952:ios:1c9380409713722c27d165',
    messagingSenderId: '244933357952',
    projectId: 'restauranteb-d5673',
    storageBucket: 'restauranteb-d5673.appspot.com',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE_qJqdkBliD0QdCXA5ot3I9RQU0QHw0I',
    appId: '1:244933357952:web:1ad7f6b1334105f227d165',
    messagingSenderId: '244933357952',
    projectId: 'restauranteb-d5673',
    authDomain: 'restauranteb-d5673.firebaseapp.com',
    storageBucket: 'restauranteb-d5673.appspot.com',
  );
}
